### PR TITLE
Add SASL (PLAIN) support

### PR DESCRIPTION
**Pull request by 42wim**
Implements sasl support for the PLAIN mechanism.
(http://ircv3.net/specs/extensions/sasl-3.1.html)

Allows connecting to freenode from restricted hosts (like AWS)

### CODE REVIEW

**Comment by thoj** [comment]
Looks pretty good to me. Any chance of adding a few tests?

**Comment by 42wim** [comment]
I'll see what I can do :-)

**Comment by 42wim** [comment]
It's kinda hard, because to test it you have to register an account on freenode. 
And you don't want to put the credentials on github.

We could do something like below, which passes the test with valid credentials and also passes the test when the credentials are empty. Fails the test when credentials are invalid.

Comments?

```
var (
    SASLLogin    = "validaccount"
    SASLPassword = "validpass"
)

func TestConnectionSASL(t *testing.T) {
    irccon := IRC("go-eventirc", "go-eventirc")
    irccon.VerboseCallbackHandler = true
    irccon.Debug = true
    irccon.UseTLS = true
    irccon.UseSASL = true
    irccon.SASLLogin = SASLLogin
    irccon.SASLPassword = SASLPassword
    irccon.TLSConfig = &tls.Config{InsecureSkipVerify: true}
    irccon.AddCallback("001", func(e *Event) { irccon.Join("#go-eventirc") })

    irccon.AddCallback("366", func(e *Event) {
        irccon.Privmsg("#go-eventirc", "Test Message SASL\n")
        time.Sleep(2 * time.Second)
        irccon.Quit()
    })

    err := irccon.Connect("irc.freenode.net:7000")
    if err != nil {
        if SASLLogin != "" {
            t.Fatal("SASL failed")
        }
        if err.Error() != "SASL authentication failed" {
            t.Fatal("SASL failed")
        }
    }
    if SASLLogin != "" {
        irccon.Loop()
    }
}
```

**Comment by thoj** [comment]
Yeah i thought about it right after i asked. It would be very hard to automatically test. Unless you implemented a skeleton IRC server with just the SASL stuff.  I suggest we just make a test that uses t.SkipNow() when no sasl credentials are defined. So something like your test:

```
//Define SASL Credentials to test
var (
    SASLLogin    = ""
    SASLPassword = ""
)

func TestConnectionSASL(t *testing.T) {
    if (SASLLogin == "") {
      t.SkipNow()
    }
    irccon := IRC("go-eventirc", "go-eventirc")
    irccon.VerboseCallbackHandler = true
    irccon.Debug = true
    irccon.UseTLS = true
    irccon.UseSASL = true
    irccon.SASLLogin = SASLLogin
    irccon.SASLPassword = SASLPassword
    irccon.TLSConfig = &tls.Config{InsecureSkipVerify: true}
    irccon.AddCallback("001", func(e *Event) { irccon.Join("#go-eventirc") })

    irccon.AddCallback("366", func(e *Event) {
        irccon.Privmsg("#go-eventirc", "Test Message SASL\n")
        time.Sleep(2 * time.Second)
        irccon.Quit()
    })

    err := irccon.Connect("irc.freenode.net:7000")
    if err != nil {
            t.Fatal("SASL failed")
    }
//...etc?
}
```

**Comment by thoj** [comment]
Maybe even better to use ENV variables?

**Comment by 42wim** [comment]
PR updated with the test (using env variables)

**Comment by thoj** [comment]
Super :dancer: 

Thanks :)

**Pull request merged**
