### PR TITLE
Adding ConnectCallback and DisconnectCallback

### PR DESCRIPTION
**Pull request by tbarron-xyz**
My application is connecting to a not-particularly-stable IRC server, so I added some hooks to handle connect/disconnect. (Rather than just print the connect/disconnect message to the log/console.)

Usage is:

```
ircclient := irc.IRC("mynick", "mynick")
ircclient.Password = "mypassword"
ircclient.ConnectCallback = func () { /* do stuff */ }
ircclient.DisconnectCallback = func (err error) { /* do stuff */ }
ircclient.Connect("irc.twitch.tv:6667")
```

### CODE REVIEW

**Comment by thoj** [comment]
Interesting. Is the reason you need this that the reconnect logic is not working? I can absolutely see the use case for this. 
28. jul. 2016 9.54 p.m. skrev tbarron-xyz <notifications@github.com>:

**Comment by tbarron-xyz** [comment]
@thoj It's reconnecting properly, but I need my program to do some additional things when this happens. (Rejoining channels, for example.)

**Comment by thoj** [comment]
Ah I see. Thanks :-) I'm trying to think how to hook this into the existing irc_callback.go code instead of adding extra stuff to the Connection struct
28. jul. 2016 10.25 p.m. skrev tbarron-xyz <notifications@github.com>:@thoj It's reconnecting properly, but I need my program to do some additional things when this happens. (Rejoining channels, for example.)

**Comment by tbarron-xyz** [comment]
Maybe something like this?

```
func (irc *Connection) LoopWithHooks(connectHook func (), disconnectHook func (err)) {
    errChan := irc.ErrorChan()
    for !irc.quit {
        err := <-errChan
        irc.Log.Printf("Error, disconnected: %s\n", err)
        if disconnectHook != nil {
            disconnectHook(err)
        }
        for !irc.quit {
            if err = irc.Reconnect(); err != nil {
                irc.Log.Printf("Error while reconnecting: %s\n", err)
                time.Sleep(60 * time.Second)
            } else {
                if connectHook != nil {
                    connectHook()
                }
                errChan = irc.ErrorChan()
                break
            }
        }
    }
}

func (irc *Connect) Loop () {
    irc.LoopWithHooks(nil, nil)
}
```

**Comment by iafan** [comment]
Just wanted to chime in here. I also noticed that after reconnecting to the server the bot wouldn't join back the channels, so went here to find an existing issue of file a new one.

@tbarron-xyz is the need to rejoin the channels the only reason justifying these callbacks for you? Or do you have some extra stuff to do on server reconnect?

If talking specifically about automatically rejoining channels (which I think is a primary use case for most IRC bots), I think one could come up with simpler API — e.g. functions `Join(name)`, `Part(name)` and , `PartAll()` could also maintain an internal list of currently joined channels, and all these channels would be rejoined automatically on every reconnect.

**Comment by tbarron-xyz** [comment]
@iafan My app needs to stagger its rejoins because JOINs are rate limited on IRC server I'm botting. So yes, rejoining is the primary concern, but I need to provide my own hook for it.

I like your idea of internally keeping tack of currently joined channels, but it would be better to have them fire on JOIN, PART, and KICK messages from the server (any others? I'm not too familiar with the IRC spec) rather than on us sending the commands. And of course an option to disable auto-rejoining.

**Comment by thoj** [comment]
One thing i'm wondering why not fire off the JOINS in a 001 event? You could even stagger the joins using a gofunc.

**Comment by iafan** [comment]
@thoj, thanks for the suggestion! I tried it and it seems to work just fine in my particular case where I just need to re-join a few channels.

**Comment by tbarron-xyz** [comment]
Ah, I didn't think to use the 001 event. Is there anything similar for disconnects?

**Comment by thoj** [comment]
That is true.

**Comment by prologic** [comment]
FWIW I came across this PR because my application reconnects/reacts too slowly.

I noticed this finally after a few mins:

```
2017/11/06 00:58:23 --> PONG :irc.mills.io


2017/11/06 01:04:15 --> PING 1509959055246756232
2017/11/06 01:04:15 Error, disconnected: read tcp 10.0.0.115:51728->10.0.0.10:6697: read: connection reset by peer
```

This ~6m delay in realizing it lost its connection kind of sucks for my use-case. I need it to react much faster.

**Pull request closed without merging**
