### PR TITLE
Add realname support. Guard against race conditions on Disconnect

### PR DESCRIPTION
**Pull request by prologic**

### CODE REVIEW

**Comment by thoj** [comment]
Looks great! But I would really like to not change the IRC constructor. Could you do it like UseTLS and Password?

**Comment by prologic** [comment]
Yeah that's fine too. I'll amend.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
Done

**Comment by thoj** [comment]
Very good! Thanks :)

**Comment by prologic** [comment]
Ahh thank you :) I have more coming!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Pull request merged**
