### PR TITLE
IRCv3 capability negotiation and tag parsing

### PR DESCRIPTION
**Pull request by russss**
This adds the ability to negotiate arbitrary IRCv3 capabilities on connection, in accordance with the [IRCv3.1 Client Capability Negotiation spec](http://ircv3.net/specs/core/capability-negotiation-3.1.html). Capabilities to be requested can be set in `irc.RequestCaps`, and after registration the negotiated capabilities can be seen in `irc.AcknowledgedCaps`.

It also adds support for [IRCv3.2 message tags](http://ircv3.net/specs/core/message-tags-3.2.html) to the event parser.

Ref: issue #34

### CODE REVIEW

**Comment by vallard192** [comment]
Is this PR waiting on anything in particular?  Would love to see it merged.

**Comment by thoj** [comment]
Just forgot about this. Sorry 🙄

**Comment by vallard192** [comment]
No worries at all and thanks!  Loving the library so far.

**Comment by Habbie** [comment]
Note: using this negotiation breaks the SASL support from #77.

**Pull request merged**
